DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INTEGER IDENTITY PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  first_name VARCHAR(30) NULL,
  last_name VARCHAR(30) NULL,
  cancelled BOOLEAN DEFAULT 0,
  UNIQUE INDEX email_unique (email ASC));